# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build and deploy to gh-pages

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: install
        run: |
          npm ci --no-audit
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.9.0
        with:
          folder: _site
          branch: gh-pages
